imports:
    - { resource: services.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Services\:
        resource: '../../src/AppBundle/Services'
        public: true
